spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  aop:
    proxy-target-class: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA}
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30
springdoc:
  override-with-generic-response: false
